import { existsSync, openSync, readSync, closeSync } from 'node:fs';
import { versioned } from './assetVersion';

/* Cover art is served at three sizes: an 800px twin for cards, the 1200px
 * original for article heroes, and a 2400px twin for retina. Not every cover
 * has all three, and a few originals are 1456px rather than 1200px, so the
 * width descriptors are read from the files instead of assumed. Guessing them
 * is worse than omitting them: a wrong `w` makes the browser pick a file that
 * is too small and the cover renders soft.
 *
 * Generated by scripts/gen-cover-variants.mjs.
 */

/** Pixel width from a WebP header. Avoids pulling an image library into a
 *  module that runs for every card on every page. */
function webpWidth(file: string): number | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(file, 'r');
    const head = Buffer.alloc(32);
    if (readSync(fd, head, 0, 32, 0) < 30) return undefined;
    if (head.toString('ascii', 0, 4) !== 'RIFF' || head.toString('ascii', 8, 12) !== 'WEBP') return undefined;

    switch (head.toString('ascii', 12, 16)) {
      case 'VP8X':
        return head.readUIntLE(24, 3) + 1;
      case 'VP8L':
        // 14 bits of width-1, starting after the 0x2f signature byte.
        return (head.readUInt32LE(21) & 0x3fff) + 1;
      case 'VP8 ':
        return head.readUInt16LE(26) & 0x3fff;
      default:
        return undefined;
    }
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

/* Slot widths, measured from the layouts rather than guessed. The content
 * grid is max-w-6xl with px-6, so 1104px inside at full width. Each value errs
 * slightly large: a browser that picks one file up is invisible, one that
 * picks a file down renders the cover soft. */

/** A card in the three-column listing grids. */
export const CARD_SIZES = '(min-width: 1152px) 352px, (min-width: 640px) calc((100vw - 96px) / 3), calc(100vw - 48px)';
/** The lead article on /insights: five of twelve columns. */
export const FEATURED_SIZES = '(min-width: 1152px) 440px, (min-width: 768px) 40vw, calc(100vw - 48px)';
/** A cover running the full width of the content grid. */
export const HERO_SIZES = '(min-width: 1152px) 1104px, calc(100vw - 48px)';

export interface CoverSources {
  /** The original, content-hashed. Always the `src` fallback. */
  src: string | undefined;
  /** Undefined when the cover has no twins, so the attribute is left off. */
  srcset: string | undefined;
  /** Undefined alongside `srcset`: `sizes` without `srcset` does nothing. */
  sizes: string | undefined;
}

const cache = new Map<string, Omit<CoverSources, 'sizes'>>();

/** Spread onto an `<img>`: `<img {...coverImg(cover, CARD_SIZES)} alt="" />`. */
export function coverImg(cover: string | undefined, sizes: string): CoverSources {
  const { src, srcset } = coverSources(cover);
  return { src, srcset, sizes: srcset ? sizes : undefined };
}

export function coverSources(cover?: string): Omit<CoverSources, 'sizes'> {
  if (!cover || !cover.startsWith('/')) return { src: cover, srcset: undefined };

  const hit = cache.get(cover);
  if (hit) return hit;

  const candidates = [cover.replace(/\.webp$/, '-800.webp'), cover, cover.replace(/\.webp$/, '-2400.webp')];

  const seen = new Set<string>();
  const entries: string[] = [];
  for (const path of candidates) {
    if (seen.has(path)) continue;
    seen.add(path);
    const file = `${process.cwd()}/public${path}`;
    if (!existsSync(file)) continue;
    const width = webpWidth(file);
    if (!width) continue;
    entries.push(`${versioned(path)} ${width}w`);
  }

  const out: Omit<CoverSources, 'sizes'> = {
    src: versioned(cover),
    srcset: entries.length > 1 ? entries.join(', ') : undefined,
  };
  cache.set(cover, out);
  return out;
}
