import { existsSync } from 'node:fs';
import { webpWidth } from '@wojciech/mdx-components/lib/imageRungs';
import { versioned } from './assetVersion';

/* Cover art is served at three sizes: an 800px twin for cards, the 1200px
 * original for article heroes, and a 2400px twin for retina. Not every cover
 * has all three, and a few originals are 1456px rather than 1200px, so the
 * width descriptors are read from the files instead of assumed. Guessing them
 * is worse than omitting them: a wrong `w` makes the browser pick a file that
 * is too small and the cover renders soft.
 *
 * Generated by scripts/gen-cover-variants.mjs. The header read is shared with
 * the in-article images, which need the same answer for the same reason.
 */

/* Slot widths, measured from the layouts rather than guessed. The content
 * grid is max-w-6xl with px-6, so 1104px inside at full width. Each value errs
 * slightly large: a browser that picks one file up is invisible, one that
 * picks a file down renders the cover soft. */

/** A card in the three-column listing grids. */
export const CARD_SIZES = '(min-width: 1152px) 352px, (min-width: 640px) calc((100vw - 96px) / 3), calc(100vw - 48px)';
/** The lead article on /insights: five of twelve columns. */
export const FEATURED_SIZES = '(min-width: 1152px) 440px, (min-width: 768px) 40vw, calc(100vw - 48px)';
/** A card in the two-column grids, such as the press band on /about. */
export const WIDE_CARD_SIZES = '(min-width: 1152px) 544px, (min-width: 640px) calc((100vw - 64px) / 2), calc(100vw - 48px)';
/** A cover running the full width of the content grid. */
export const HERO_SIZES = '(min-width: 1152px) 1104px, calc(100vw - 48px)';
/** The lens hero on a phone: one column, capped by max-w-2xl. Hidden from lg up. */
export const LENS_MOBILE_SIZES = '(min-width: 720px) 672px, calc(100vw - 48px)';

export interface CoverSources {
  /** The original, content-hashed. Always the `src` fallback. */
  src: string | undefined;
  /** Undefined when the cover has no twins, so the attribute is left off. */
  srcset: string | undefined;
  /** Undefined alongside `srcset`: `sizes` without `srcset` does nothing. */
  sizes: string | undefined;
}

const cache = new Map<string, Omit<CoverSources, 'sizes'>>();

/** Spread onto an `<img>`: `<img {...coverImg(cover, CARD_SIZES)} alt="" />`. */
export function coverImg(cover: string | undefined, sizes: string): CoverSources {
  const { src, srcset } = coverSources(cover);
  return { src, srcset, sizes: srcset ? sizes : undefined };
}

export function coverSources(cover?: string): Omit<CoverSources, 'sizes'> {
  if (!cover || !cover.startsWith('/')) return { src: cover, srcset: undefined };

  const hit = cache.get(cover);
  if (hit) return hit;

  const candidates = [cover.replace(/\.webp$/, '-800.webp'), cover, cover.replace(/\.webp$/, '-2400.webp')];

  const seen = new Set<string>();
  const entries: string[] = [];
  for (const path of candidates) {
    if (seen.has(path)) continue;
    seen.add(path);
    const file = `${process.cwd()}/public${path}`;
    if (!existsSync(file)) continue;
    const width = webpWidth(file);
    if (!width) continue;
    entries.push(`${versioned(path)} ${width}w`);
  }

  const out: Omit<CoverSources, 'sizes'> = {
    src: versioned(cover),
    srcset: entries.length > 1 ? entries.join(', ') : undefined,
  };
  cache.set(cover, out);
  return out;
}
