// Conventional-commit gate. JS config (not JSON) so we can ignore the one
// historical direct-to-main commit whose header exceeds the 100-char cap
// (0f988f1) without rewriting main history.
export default {
  extends: ['@commitlint/config-conventional'],
  ignores: [
    (message) =>
      message.startsWith(
        'fix(subscribe): stop the self-proxy loop killing signups, rewire form for ClientRouter, espresso emails'
      ),
  ],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'copy',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'i18n',
        'seo',
        'academy',
        'growthhub',
        'notch',
        'subscribe',
        'app',
        'insights',
        'ai-systems',
        'about',
        'work',
        'contact',
        'cv',
        'security',
        'ops',
        'agents',
        'test',
        'ci',
        'dev',
        'copy',
        'dx',
        'sprint0',
        'sprint1',
        'sprint2',
        'release',
        'deps',
        'apps',
        'favicon',
        'tokens',
        'fonts',
        'lens',
        'newsletter',
        'footer',
        'hero',
        'stack',
      ],
    ],
    'subject-case': [0],
    'subject-max-length': [2, 'always', 100],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [0],
    'footer-max-line-length': [0],
    'footer-leading-blank': [0],
  },
};
