import { closeSync, existsSync, openSync, readSync } from 'node:fs';

/* Article images are authored three ways: through <Screenshot>, through
 * <AnnotatedImage>, and as raw <img> in the MDX. Only one of those passes a
 * width, so the rungs are worked out from the files on disk instead of from
 * the props. That way a new image gets the treatment by existing, not by the
 * author remembering to declare it.
 *
 * Narrower copies are generated by scripts/gen-cover-variants.mjs and named by
 * their width.
 */

const RUNGS = [800, 1500];

/** The prose column caps at 46rem, so an in-article image renders about 736px
 *  wide and a retina reader needs roughly 1472. */
export const PROSE_SIZES = '(min-width: 1024px) 736px, calc(100vw - 48px)';

/** Pixel width from a WebP header, so that reading one does not pull an image
 *  library into a component that renders during every build. */
export function webpWidth(file: string): number | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(file, 'r');
    const head = Buffer.alloc(32);
    if (readSync(fd, head, 0, 32, 0) < 30) return undefined;
    if (head.toString('ascii', 0, 4) !== 'RIFF' || head.toString('ascii', 8, 12) !== 'WEBP') return undefined;

    switch (head.toString('ascii', 12, 16)) {
      case 'VP8X':
        return head.readUIntLE(24, 3) + 1;
      case 'VP8L':
        // 14 bits of width-1, starting after the 0x2f signature byte.
        return (head.readUInt32LE(21) & 0x3fff) + 1;
      case 'VP8 ':
        return head.readUInt16LE(26) & 0x3fff;
      default:
        return undefined;
    }
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

export interface Rungs {
  /** Undefined when there is nothing to choose between, so the attribute is
   *  left off. A srcset with one candidate only adds bytes to the HTML. */
  srcset: string | undefined;
  /** Undefined alongside `srcset`: `sizes` on its own does nothing. */
  sizes: string | undefined;
}

const cache = new Map<string, Rungs>();

export function imageRungs(src: string | undefined, sizes: string = PROSE_SIZES): Rungs {
  if (!src || !src.startsWith('/') || !src.endsWith('.webp')) return { srcset: undefined, sizes: undefined };

  const hit = cache.get(src);
  if (hit) return hit.srcset ? { ...hit, sizes } : hit;

  const publicDir = `${process.cwd()}/public`;
  const width = webpWidth(`${publicDir}${src}`);
  if (!width) {
    const miss = { srcset: undefined, sizes: undefined };
    cache.set(src, miss);
    return miss;
  }

  const entries = RUNGS.filter((w) => w < width)
    .map((w) => ({ w, path: src.replace(/\.webp$/, `-${w}.webp`) }))
    .filter(({ path }) => existsSync(`${publicDir}${path}`))
    .map(({ w, path }) => `${path} ${w}w`);

  entries.push(`${src} ${width}w`);

  const out: Rungs = entries.length > 1 ? { srcset: entries.join(', '), sizes } : { srcset: undefined, sizes: undefined };
  cache.set(src, out);
  return out;
}
