export type AppStatus = 'live' | 'in-progress' | 'private-mvp' | 'private-beta' | 'private' | 'soon';
export type AppFilter = 'b2b' | 'consumer' | 'booking' | 'brand' | 'productivity';

export interface AppEntry {
  id: string;
  name: string;
  initials: string;
  category: string;
  badge: string;
  tagline: { en: string; pl: string; it: string };
  tags: string;
  searchName: string;
  tech: { label: string; accent?: true }[];
  url?: string;
  urlLabel?: { en: string; pl: string; it: string };
  status: AppStatus;
  // Caption on the designed tile, for entries with no screenshot to show.
  tileNote?: string;
  // Color palette — drives card-screen gradients, icon box, app-icon chip
  palette: BRAND_PALETTE;
  icon: string; // inner SVG markup (no outer <svg>)
}

const ICON = {
  cart: '<circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>',
  trendUp: '<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/>',
  users: '<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
  home: '<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',
  music: '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
  pin: '<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/>',
  target: '<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',
  monitor: '<rect x="2" y="3" width="20" height="13" rx="2"/><path d="M2 19h20"/><path d="M8 23h8"/><rect x="10" y="5" width="4" height="2" rx="1" fill="currentColor" stroke="none" opacity="0.6"/>',
  truck: '<rect x="1" y="3" width="15" height="13" rx="2"/><path d="M16 8h4l3 4v3h-7V8z"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/>',
  list: '<path d="M3 6h18M3 12h18M3 18h18"/><circle cx="7" cy="6" r="1" fill="currentColor" stroke="none"/><circle cx="7" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="7" cy="18" r="1" fill="currentColor" stroke="none"/>',
  lightning: '<path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>',
  network: '<circle cx="12" cy="5" r="2.5"/><circle cx="5" cy="19" r="2.5"/><circle cx="19" cy="19" r="2.5"/><path d="M12 7.5v4M12 11.5 6.6 16.9M12 11.5l5.4 5.4"/>',
  bookmark: '<path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
  play: '<circle cx="12" cy="12" r="10"/><polygon points="10 8 16 12 10 16 10 8"/>',
  terminal: '<rect x="2" y="4" width="20" height="16" rx="2"/><polyline points="7 9 10 12 7 15"/><path d="M13 15h4"/>',
  grid: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
  layers: '<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>',
};

const BRAND_PALETTE = {
  screenFrom: '#15151a', screenTo: '#0b0b0f',
  glowRgba: 'rgba(235,255,0,0.06)',
  iconFrom: '#1c1c22', iconTo: '#121217',
  shadowRgba: 'rgba(0,0,0,0.45)',
  chipBg: 'rgba(235,255,0,0.14)',
};

export const apps: AppEntry[] = [
  {
    id: 'sabiszop',
    name: 'SabiSzop',
    initials: 'SS',
    category: 'Marketplace · B2C',
    badge: 'Marketplace',
    tagline: {
      en: 'A shopping-list app that reads your receipts and helps plan the next trip.',
      pl: 'Smart listy zakupów, paragony i przepisy. Grocery inspired dark glassmorphism UI z AI sugestiami.',
      it: 'Liste della spesa intelligenti, scontrini e ricette. UI glassmorphism con suggerimenti AI.',
    },
    tags: 'consumer pwa react typescript supabase',
    searchName: 'sabiszop sabi szop grocery shopping',
    tech: [{ label: 'React 18' }, { label: 'TypeScript' }, { label: 'Supabase' }, { label: 'Recharts' }, { label: 'Netlify' }],
    url: 'https://sabiszop.netlify.app/listy',
    urlLabel: { en: 'Demo', pl: 'Demo', it: 'Demo' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.cart,
  },
  {
    id: 'growthhub',
    name: 'GrowthHub',
    initials: 'GH',
    category: 'Growth · B2B SaaS',
    badge: 'SaaS',
    tagline: {
      en: 'A marketing dashboard for scoring leads and tracking revenue. Being rebuilt right now.',
      pl: 'Growth dashboard dla demand gen, lead scoringu i revenue trackingu w jednym miejscu. Aktualnie przepisywany na Claude, bez wcześniejszego brandingu.',
      it: 'Growth dashboard per demand gen, lead scoring e revenue tracking in un unico posto. Attualmente in ricostruzione su Claude, senza branding precedente.',
    },
    tags: 'b2b saas growth marketing analytics dashboard',
    searchName: 'growthhub growth hub dashboard',
    tech: [{ label: 'React' }, { label: 'TypeScript' }, { label: 'Claude' }],
    url: 'https://gh.wojciech.io/demo/',
    urlLabel: { en: 'Demo', pl: 'Demo', it: 'Demo' },
    status: 'in-progress',
    palette: BRAND_PALETTE,
    icon: ICON.trendUp,
  },
  {
    id: 'relora',
    name: 'Relora',
    initials: 'RE',
    category: 'Relationship OS · Public sector',
    badge: 'SaaS',
    tagline: {
      en: 'A simple CRM for public-sector property teams: who to contact and what happens next.',
      pl: 'System do zarządzania relacjami dla samorządowych zespołów nieruchomości. Kontakty, kontekst właściciela, status komunikacji i następne kroki w jednym widoku.',
      it: 'Sistema operativo per le relazioni dei team immobiliari della pubblica amministrazione. Contatti, contesto proprietario, stato della comunicazione e azioni successive in un\'unica vista.',
    },
    tags: 'b2b saas ai workflow crm ops dashboard public-sector',
    searchName: 'relora crm relacje nieruchomosci samorzad ops dashboard',
    tech: [{ label: 'React' }, { label: 'TypeScript' }, { label: 'Vercel' }],
    url: 'https://relora-jet.vercel.app/',
    urlLabel: { en: 'Demo', pl: 'Demo', it: 'Demo' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.network,
  },
  {
    id: 'kade',
    name: 'Kade',
    initials: 'KA',
    category: 'Mac Utility · macOS native',
    badge: 'macOS',
    tagline: {
      en: 'A Mac app for parking links you are not ready to open yet. Stays on your machine.',
      pl: 'Spokojniejszy sposób na trzymanie linków. Przechowuje te, które potrzebują kontekstu, zanim znów warto je otworzyć. Lokalnie, bez chmury.',
      it: 'Un modo più tranquillo di conservare i link. Tiene quelli che hanno bisogno di contesto prima di valere una seconda apertura. Local-first, senza cloud.',
    },
    tags: 'productivity macos native swift desktop utility links local-first',
    searchName: 'kade linki bookmarks macos local-first utility',
    tech: [{ label: 'SwiftUI', accent: true }, { label: 'macOS', accent: true }, { label: 'Local-first' }],
    url: 'https://wojciech.io/apps/kade/',
    urlLabel: { en: 'Landing', pl: 'Strona', it: 'Landing' },
    status: 'private-mvp',
    palette: BRAND_PALETTE,
    icon: ICON.bookmark,
  },
  {
    id: 'academy',
    name: 'Academy',
    initials: 'AC',
    category: 'Program · AI for GTM',
    badge: 'Program',
    tagline: {
      en: 'A video course on using AI for marketing and sales. 36 episodes, no fluff.',
      pl: 'AI dla GTM od operatora, nie ze slajdów. 36 odcinków o marketingu, sprzedaży i pracy founderów B2B. Procesy, nie nazwy narzędzi.',
      it: 'AI per il GTM insegnata da un operatore, non dalle slide. 36 episodi su marketing, vendite e lavoro dei founder B2B. Processi, non nomi di strumenti.',
    },
    tags: 'ai gtm program education course marketing sales',
    searchName: 'academy akademia kurs program ai gtm szkolenie',
    tech: [{ label: 'Astro' }, { label: 'Stripe' }, { label: 'Cloudflare' }],
    url: 'https://wojciech.io/apps/academy/',
    urlLabel: { en: 'Open', pl: 'Otwórz', it: 'Apri' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.play,
  },
  {
    id: 'gtm-starter-pack',
    name: 'GTM Agent Starter Pack',
    initials: 'GS',
    category: 'Open source · Claude Code',
    badge: 'Open source',
    tagline: {
      en: 'An open-source kit for building your own AI marketing agents with Claude Code.',
      pl: 'Otwartoźródłowy starter pack do budowania agentów AI GTM na Claude Code. Dla operatorów, którzy chcą wdrażać AI-native workflow bez zaczynania od zera.',
      it: 'Starter pack open source per costruire agenti AI GTM con Claude Code. Per operatori che vogliono realizzare workflow AI-native senza partire da zero.',
    },
    tags: 'b2b ai gtm open-source claude-code agents mcp automation',
    searchName: 'gtm starter pack claude code agent open source repo github',
    tech: [{ label: 'Claude Code', accent: true }, { label: 'MCP', accent: true }, { label: 'Markdown' }],
    url: 'https://github.com/wojciechluszczynski/gtm-agent-repo',
    urlLabel: { en: 'GitHub', pl: 'GitHub', it: 'GitHub' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.terminal,
  },
  {
    id: 'an-projekt',
    name: 'AN Projekt',
    initials: 'AN',
    category: 'Website · Interior Design',
    badge: 'Website',
    tagline: {
      en: 'A website I built for an interior-design studio.',
      pl: 'Strona internetowa pracowni projektowania wnętrz. Wnętrza dopasowane do Twojego życia.',
      it: 'Sito web dello studio di interior design. Interni su misura per la tua vita.',
    },
    tags: 'brand website interior design react vite lovable strona-www',
    searchName: 'an projekt an-projekt strona internetowa website',
    tech: [{ label: 'React' }, { label: 'Vite' }, { label: 'Lovable' }, { label: 'Tailwind' }],
    url: 'https://anprojekt.com.pl/',
    urlLabel: { en: 'Open', pl: 'Otwórz', it: 'Apri' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.home,
  },
  {
    id: 'ciryam',
    name: 'Ciryam',
    initials: 'CI',
    category: 'Website · Music Band',
    badge: 'Website',
    tagline: {
      en: 'A website for a Polish rock band: tour dates, music, tickets and merch.',
      pl: 'Oficjalna strona polskiego zespołu rockowego z koncertami, muzyką, biletami i sklepem z merch.',
      it: 'Sito ufficiale di una band rock polacca con concerti, musica, biglietti e negozio merch.',
    },
    tags: 'brand website music band rock react vite',
    searchName: 'ciryam band music website strona',
    tech: [{ label: 'React' }, { label: 'Vite' }, { label: 'Tailwind' }],
    url: 'https://ciryam.lovable.app/',
    urlLabel: { en: 'Open', pl: 'Otwórz', it: 'Apri' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.music,
  },
  {
    id: 'dzialkometr',
    name: 'Działkometr',
    initials: 'DZ',
    category: 'Real Estate · PWA',
    badge: 'PWA',
    tagline: {
      en: 'An app that estimates what a plot of land is worth.',
      pl: 'Kalkulator wartości działek z analizą lokalizacji, mediami, MPZP i wyceną nieruchomości.',
      it: 'Calcolatore del valore del terreno con analisi posizione, utenze e valutazione.',
    },
    tags: 'consumer pwa react vite supabase real-estate nieruchomosci dzialka kalkulator',
    searchName: 'dzialkomierz dzialka nieruchomosci kalkulator',
    tech: [{ label: 'React' }, { label: 'Vite' }, { label: 'Supabase' }, { label: 'Mapbox' }, { label: 'Netlify' }],
    // No link: due for a rebuild, so the current build isn't worth showing.
    status: 'in-progress',
    tileNote: 'Rebuild in progress',
    palette: BRAND_PALETTE,
    icon: ICON.pin,
  },
  {
    id: 'ads-assistant',
    name: 'Ads Assistant',
    initials: 'AA',
    category: 'Marketing AI · B2B SaaS',
    badge: 'SaaS',
    tagline: {
      en: 'A Google Ads dashboard that ranks leads by how well they fit your ideal customer.',
      pl: 'Dashboard Google Ads z AI ICP lead scoringiem (0-100). Przesuwa optymalizację z CPL na CPL-ICP-fit.',
      it: 'Dashboard Google Ads con AI ICP lead scoring (0-100). Sposta l\'ottimizzazione da CPL a CPL-ICP-fit.',
    },
    tags: 'b2b saas ai google-ads marketing automation analytics icp',
    searchName: 'ads assistant google ads dashboard marketing ai performance',
    tech: [{ label: 'React' }, { label: 'TypeScript' }, { label: 'Vite' }, { label: 'Tailwind' }, { label: 'Vercel' }],
    url: 'https://ads-assistant-three.vercel.app',
    urlLabel: { en: 'Open', pl: 'Otwórz', it: 'Apri' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.target,
  },
  {
    id: 'notchcue',
    name: 'NotchCue',
    initials: 'NC',
    category: 'Desktop Utility · macOS',
    badge: 'macOS',
    tagline: {
      en: 'A Mac teleprompter that hides your notes under the camera notch, so you keep eye contact on calls.',
      pl: 'Natywny teleprompter macOS umieszczający prywatne notatki pod notchem kamery MacBooka.',
      it: 'Teleprompter nativo macOS che posiziona note private sotto il notch della fotocamera MacBook.',
    },
    tags: 'productivity macos native swift desktop utility teleprompter privacy local-first',
    searchName: 'notchcue notch cue macos teleprompter prompter',
    tech: [{ label: 'Swift 5.10' }, { label: 'AppKit' }, { label: 'AVFoundation' }, { label: 'macOS 14+' }],
    url: 'https://notch.wojciech.io',
    urlLabel: { en: 'Landing', pl: 'Strona', it: 'Landing' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.monitor,
  },
  {
    id: 'camper-rental',
    name: 'Camper Rental',
    initials: 'CR',
    category: 'Booking Engine · Consumer',
    badge: 'Booking',
    tagline: {
      en: 'A booking site for renting out campers, with live pricing and availability.',
      pl: 'Booking engine do wynajmu kamperów z dynamicznymi cenami, zarządzaniem dostępnością i czystym flow rezerwacji.',
      it: 'Motore di prenotazione per noleggio camper con prezzi dinamici, gestione disponibilità e flusso di prenotazione semplice.',
    },
    tags: 'booking consumer react typescript supabase vercel rental',
    searchName: 'camper rental kamperownia booking engine',
    tech: [{ label: 'React' }, { label: 'TypeScript' }, { label: 'Supabase' }, { label: 'Vercel' }],
    url: 'https://camper-rental-weld.vercel.app/',
    urlLabel: { en: 'Open', pl: 'Otwórz', it: 'Apri' },
    status: 'live',
    palette: BRAND_PALETTE,
    icon: ICON.truck,
  },
  {
    id: 'klaro',
    name: 'Klaro',
    initials: 'KL',
    category: 'Mac Utility · macOS native',
    badge: 'macOS',
    tagline: {
      en: 'A Mac cleaning app, like CleanMyMac, except everything it clears goes to Trash first.',
      pl: 'Lokalny audyt Maca z podglądem czyszczenia i raportem HTML. Pliki trafiają do Kosza. Nic nie znika po cichu.',
      it: 'Audit Mac locale con anteprima pulizia e report HTML. I file vanno nel Cestino, niente sparisce in silenzio.',
    },
    tags: 'productivity macos native swift desktop utility cleaner storage privacy local-first',
    searchName: 'klaro mac cleaner cleanup storage utility swift swiftui macos native',
    tech: [{ label: 'SwiftUI', accent: true }, { label: 'macOS', accent: true }, { label: 'CLI' }, { label: 'Codex' }],
    status: 'private-mvp',
    palette: BRAND_PALETTE,
    icon: ICON.list,
  },
  {
    id: 'wojciech-coach',
    name: 'Wojciech Coach',
    initials: 'WC',
    category: 'Fitness · iPhone · Apple Watch · Mac',
    badge: 'iOS / watchOS / Mac',
    tagline: {
      en: 'A running and fitness coach for iPhone and Apple Watch, like Strava but private.',
      pl: 'Prywatny trener biegania i aktywności dla ekosystemu Apple. Apple Health, trening live na Watchu, plan adaptacyjny, mapy, odznaki i analiza na Macu.',
      it: 'Coach privato per corsa e attività per l\'ecosistema Apple. HealthKit, allenamento live su Watch, piano adattivo, mappe, badge e analisi su Mac.',
    },
    tags: 'consumer ios macos watchos health fitness swift apple xcode codex',
    searchName: 'wojciech coach running health apple watch iphone fitness tracker coaching',
    tech: [{ label: 'SwiftUI', accent: true }, { label: 'HealthKit', accent: true }, { label: 'watchOS', accent: true }, { label: 'Xcode' }, { label: 'Codex' }],
    status: 'private-beta',
    palette: BRAND_PALETTE,
    icon: ICON.lightning,
  },
  {
    id: 'content-hub',
    name: 'Content Hub',
    initials: 'CH',
    category: 'Content Ops · AI',
    badge: 'AI',
    tagline: {
      en: 'An AI content hub. Built for a client, so it stays unlinked and undescribed.',
      pl: 'Hub contentowy z AI. Projekt klienta, więc bez linku i bez szczegółów.',
      it: 'Hub di contenuti con AI. Lavoro per un cliente, quindi senza link e senza dettagli.',
    },
    tags: 'ai content marketing hub base44 private',
    searchName: 'content hub ai content marketing',
    tech: [{ label: 'Base44', accent: true }, { label: 'AI' }],
    // No link and no client detail by design: the engagement stays masked.
    status: 'private',
    tileNote: 'Client work, masked',
    palette: BRAND_PALETTE,
    icon: ICON.network,
  },
  {
    id: 'mini-apps',
    name: 'Mini Apps',
    initials: 'MA',
    category: 'Utility apps · Early builds',
    badge: 'Early',
    tagline: {
      en: 'The first three ideas I built: Działka+, Paczka+, Resume+. Early versions, still being worked on.',
      pl: 'Pierwsze trzy pomysły, które zbudowałem: Działka+, Paczka+, Resume+. Wczesne wersje, wciąż rozwijane.',
      it: 'Le prime tre idee che ho costruito: Działka+, Paczka+, Resume+. Versioni iniziali, ancora in sviluppo.',
    },
    tags: 'consumer utility early dzialka paczka resume mini apps',
    searchName: 'mini apps dzialka paczka resume pierwsze pomysly',
    // No link: the case study points back at this very page.
    tech: [],
    status: 'in-progress',
    tileNote: 'First ideas, in development',
    palette: BRAND_PALETTE,
    icon: ICON.grid,
  },
];
